### ISSUE TITLE
Installation of GlusterFS fails

### ISSUE THREAD

**Issue by CodingSpiderFox** [geerlingguy/ansible-role-glusterfs#34]
Hi,
The installation of GlusterFS fails.

I created a role that I want to roll out to some nodes in my home lab.

The role is defined as follows:

```
---
# tasks file for single_data_volume
- include_role:
    name: gluster-node
    tasks_from: single_data_volume
  vars:
    gluster_brick_dir: '/data1'
    gluster_mount_dir: '/gluster_volume1'
    gluster_brick_name: 'brick1'

- include_role:
    name: gluster-node-partition
    tasks_from: default_partitioning

- name: Create default partitioning
  include_role:
    name: gluster-node-partition

- name: Create gluster volume for partition 1
  include_role:
    name: gluster-node
  vars:
    gluster_brick_dir: /data1/glusterbrick1
    gluster_mount_dir: /gluster_volume1
    gluster_brick_name: 'brick1'

- name: Create gluster volume for partition 2
  include_role:
    name: gluster-node
  vars:
    gluster_brick_dir: /data1/glusterbrick2
    gluster_mount_dir: /gluster_volume2
    gluster_brick_name: 'brick2'

- name: Create gluster volume for partition 3
  include_role:
    name: gluster-node
  vars:
    gluster_brick_dir: /data1/glusterbrick3
    gluster_mount_dir: /gluster_volume3
    gluster_brick_name: 'brick3'
```

It makes use of another role I defined which contains the code from you tutorial (https://www.jeffgeerling.com/blog/simple-glusterfs-setup-ansible)

```
---
# tasks file for single_data_volume
- include_role:
    name: gluster-node-partition
    tasks_from: default_partitioning

- include_role:
    name: geerlingguy.glusterfs

- name: Install glusterfs
  include_role:
    name: geerlingguy.glusterfs

- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"
  become: true

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_dir }}"
    replicas: 2
    cluster: "{{ groups.storageservers | join(',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
  become: true
```

I do the rollout using the following command:

`ansible-playbook -i inventories/playground/hosts.yaml site.yml -K`

This is the error message I get:

```
fatal: [node2]: FAILED! => {"changed": false, "msg": "'/usr/bin/apt-mark manual dirmngr' failed: E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "rc": 100, "stderr": "E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "stderr_lines": ["E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)", "E: Failed to write temporary StateFile /var/lib/apt/extended_states"], "stdout": "dirmngr set to manually installed.\n", "stdout_lines": ["dirmngr set to manually installed."]}
fatal: [node1]: FAILED! => {"changed": false, "msg": "'/usr/bin/apt-mark manual dirmngr' failed: E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "rc": 100, "stderr": "E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "stderr_lines": ["E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)", "E: Failed to write temporary StateFile /var/lib/apt/extended_states"], "stdout": "dirmngr set to manually installed.\n", "stdout_lines": ["dirmngr set to manually installed."]}
```

Both nodes run latest Ubuntu 18.04 server edition.

What do I need to do to make it work?
