### ISSUE TITLE
IPC connect call failed - in task: Ensure PPA for GlusterFS is present. (Ubuntu 22)

### ISSUE THREAD

**Issue by GREEB** [geerlingguy/ansible-role-glusterfs#48]
Hello Jeff, i've been using your roles a lot and this one sometimes give me an error in the task `Ensure PPA for GlusterFS is present`
This only happens sometimes and may be a problem with my hoster(hetzner) or other things on my Ubuntu box.

vars:
```yml
glusterfs_default_release: ""
glusterfs_ppa_use: true
glusterfs_ppa_version: "10"
```

error
```yml
TASK [geerlingguy.glusterfs : Ensure PPA for GlusterFS is present.] ****************************************************************************
fatal: [data-01-5c156b41-1c43-5588-8b28-d382b21ba464]: FAILED! => changed=false 
  cmd: /usr/bin/apt-key adv --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 F7C73FCC930AC9F83B387A5613E01B7B3FE869A9
  msg: |-
    Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
    gpg: key 13E01B7B3FE869A9: public key "Launchpad PPA for Gluster" imported
    gpg: can't connect to the agent: IPC connect call failed
    gpg: Total number processed: 1
    gpg:               imported: 1
  rc: 2
  stderr: |-
    Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
    gpg: key 13E01B7B3FE869A9: public key "Launchpad PPA for Gluster" imported
    gpg: can't connect to the agent: IPC connect call failed
    gpg: Total number processed: 1
    gpg:               imported: 1
  stderr_lines: <omitted>
  stdout: |-
    Executing: /tmp/apt-key-gpghome.fRR92Wrx6D/gpg.1.sh --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 F7C73FCC930AC9F83B387A5613E01B7B3FE869A9
  stdout_lines: <omitted>
```

This may be a problem with me running the playbook too many times in development but i don't know just wanted to post maybe you have a idea for a workaround to ensure the task won't fail.

Replication: Unfortunately i am not able to replicate this.

edit: without ppa i have no issues.

Thanks for all your work!
